import { chromium } from '@playwright/test';
import fs from 'node:fs';
fs.mkdirSync('test-results',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.goto('http://127.0.0.1:3001/',{waitUntil:'networkidle'});
await page.waitForTimeout(3500);
await page.screenshot({path:'test-results/home-desktop.png'});
console.log(JSON.stringify({title:await page.title(),text:(await page.locator('body').innerText()).slice(0,700),canvases:await page.locator('canvas').count(),errors},null,2));
await browser.close();
